// ================================================================
// MYSTERIUM FIDEI — Shared Type Definitions
// ================================================================
// These types are the single source of truth for every piece
// of data that flows through the app — from the API to the
// web frontend to the iOS app.
//
// WHY THIS MATTERS: If the shape of a LiturgicalDay changes,
// you change it here and TypeScript immediately flags every
// file in every app that uses it. No runtime surprises.
// ================================================================

// ----------------------------------------------------------------
// LITURGICAL CALENDAR
// ----------------------------------------------------------------

/**
 * Which form of the Roman Rite we are describing.
 * EF = Extraordinary Form (pre-1962 Tridentine)
 * OF = Ordinary Form (post-1970 Novus Ordo)
 */
export type LiturgicalForm = 'EF' | 'OF'

/**
 * The liturgical season — drives colour theming throughout the UI.
 */
export type LiturgicalSeason =
  | 'Advent'
  | 'Christmas'
  | 'Ordinary Time'
  | 'Lent'
  | 'Holy Week'
  | 'Easter'
  | 'Pentecost'

/**
 * Vestment colour — shown in the date bar.
 */
export type VestmentColour =
  | 'green'
  | 'purple'
  | 'white'
  | 'red'
  | 'rose'
  | 'black'
  | 'gold'

/**
 * A saint's feast day entry.
 * Both EF and OF calendars produce these.
 */
export interface Saint {
  id: string
  name: string
  feastDate: string           // ISO date e.g. "2026-05-16"
  form: LiturgicalForm        // which calendar this appears in
  rank: string                // e.g. "Double", "Memorial"
  category: SaintCategory[]
  description?: string        // short biography
  patronOf?: string[]
}

export type SaintCategory =
  | 'Martyr'
  | 'Doctor'
  | 'Bishop'
  | 'Priest'
  | 'Religious'
  | 'Mystic'
  | 'Layperson'
  | 'Virgin'
  | 'Abbot'
  | 'Missionary'
  | 'Pope'

/**
 * A scripture reading — reference plus resolved Douay-Rheims text.
 */
export interface Reading {
  reference: string           // e.g. "Sirach 17:1-15"
  book: string
  chapter: number
  verseStart: number
  verseEnd: number
  text: string                // full passage from Douay-Rheims JSON
  translation: 'Douay-Rheims' | 'CPDV' | 'Vulgate'
}

/**
 * One Hour of the Divine Office.
 * EF: full text from Divinum Officium (self-hosted Docker)
 * OF: metadata + deep link out (ICEL text is under copyright)
 */
export interface OfficeHour {
  name:
    | 'Matins'
    | 'Lauds'
    | 'Prime'
    | 'Terce'
    | 'Sext'
    | 'None'
    | 'Vespers'
    | 'Compline'
  form: LiturgicalForm
  fullText?: string           // EF only — from Divinum Officium
  externalUrl?: string        // OF only — link to divineoffice.org
  patristicReading?: {
    author: string            // e.g. "St. Augustine of Hippo"
    work: string              // e.g. "Sermon 34 on the Psalms"
    text: string
  }
}

/**
 * The complete data bundle for one calendar day.
 * This is what GET /api/daily returns to both
 * the web app and the iOS app.
 */
export interface LiturgicalDay {
  date: string                // ISO date "2026-05-16"
  form: LiturgicalForm
  season: LiturgicalSeason
  weekNumber: number
  psalterWeek: number         // 1–4 cycle
  vestmentColour: VestmentColour
  saints: Saint[]
  firstReading?: Reading
  psalm?: Reading
  secondReading?: Reading     // Sundays only
  gospel: Reading
  office: OfficeHour[]
  servusSynthesis?: string    // AI thematic summary — generated by Servus
}

// ----------------------------------------------------------------
// NOTES
// ----------------------------------------------------------------

/**
 * The five study disciplines of Mysterium Fidei.
 * Every note belongs to exactly one discipline.
 */
export type Discipline =
  | 'Philosophy'
  | 'Apologetics'
  | 'Bible'
  | 'Theology'
  | 'Spirituality'

/**
 * A note as stored in the database.
 * Body is stored as TipTap/ProseMirror JSON —
 * readable by both the web editor and iOS via the API.
 * inkData is PencilKit drawing stored as base64 —
 * only present when the user made Pencil annotations.
 */
export interface Note {
  id: string
  userId: string
  title: string
  discipline: Discipline
  body: Record<string, unknown>  // ProseMirror JSON
  inkData?: string               // PencilKit PKDrawing as base64
  tags: string[]
  linkedSaintId?: string
  linkedDate?: string
  createdAt: string
  updatedAt: string
}

// ----------------------------------------------------------------
// FLASHCARDS
// ----------------------------------------------------------------

export interface Flashcard {
  id: string
  noteId: string
  userId: string
  discipline: Discipline
  question: string
  answer: string
  // SM-2 spaced repetition fields
  interval: number            // days until next review
  easeFactor: number          // difficulty multiplier (starts at 2.5)
  repetitions: number         // total times reviewed
  nextReviewDate: string
  lastReviewDate?: string
}

export type FlashcardRating = 'Hard' | 'Good' | 'Easy'

// ----------------------------------------------------------------
// SERVUS AI
// ----------------------------------------------------------------

export interface ServusMessage {
  role: 'user' | 'assistant'
  content: string
}

export interface ServusRequest {
  messages: ServusMessage[]
  context: {
    currentNote?: Note
    currentDay?: LiturgicalDay
    discipline?: Discipline
  }
}

export interface ServusResponse {
  message: string
  suggestedFlashcards?: Pick<Flashcard, 'question' | 'answer' | 'discipline'>[]
}

// ----------------------------------------------------------------
// API RESPONSE WRAPPER
// ----------------------------------------------------------------

/**
 * Every API endpoint returns this shape.
 * Consistent contract — web and iOS always know
 * where to find data and where to find errors.
 */
export interface ApiResponse<T> {
  success: boolean
  data?: T
  error?: {
    code: string
    message: string
  }
}